-- AlterTable
ALTER TABLE "User" ADD COLUMN "currentStreak" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "longestStreak" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "lastStudyDate" DATETIME;
ALTER TABLE "User" ADD COLUMN "totalStudyDays" INTEGER NOT NULL DEFAULT 0;
